version: '2'

engines:
  python:
    enabled: true
    version: "3.10.6"
    config:
      pycodestyle:
        max_line_length: 120
      pylint:
        enabled: true
        config:
          ignore:
            - tests
          messages_only: true
      bandit:
        enabled: true
    coverage:
      enabled: true
      output_format: "lcov"
      path: "coverage.xml"
      min_coverage: 80


checks:
  duplication:
    enabled: true
    config:
      languages:
        - python
    exclude_paths:
      - 'tests/**'
      - '**/.venv/**'
      - '**/myenv/**'


  test_coverage:
    enabled: true
    output_format: "lcov"
    path: "tests/"
    min_coverage: 80
