version: "2"
plugins:
  pep8:
    enabled: true
  duplication:
    enabled: true
  radon:
    enabled: true
  mccabe:
    enabled: true
  pylint:
    enabled: true
    config:
      skip:
        - "**/*.html"
        - "**/*.md"
        - "**/*.txt"
  safety:
    enabled: true
  bandit:
    enabled: true
  codeclimate-test-reporter:
    enabled: true
    output:
      format: "lcov"
      reports:
        - "lcov"
      path: "coverage/lcov.info"
    exclude:
      - "**/.venv/**"
      - "**/myenv/**"
