version: '2'

plugins:
  python:
    enabled: true
    config:
      pycodestyle:
        max_line_length: 120
      pylint:
        enabled: true
        config:
          ignore:
            - tests
          messages_only: true
      bandit:
        enabled: true

checks:
  duplication:
    enabled: true
    config:
      languages:
        - python
    exclude_paths:
      - 'tests/**'
      - '**/.venv/**'
      - '**/myenv/**'
