version: '2'

plugins:
  pylint:
    enabled: true
  bandit:
    enabled: true
  codeclimate-pytest:
    enabled: true

engines:
  python:
    enabled: true
  codeclimate-python:
    enabled: true

checks:
  duplication:
    enabled: true
    config:
      languages:
        - python
    exclude_paths:
      - 'tests/**'
      - '**/.venv/**'
      - '**/myenv/**'

ratings:
  paths:
    - "**.py"
  include_paths:
    - "**.py"
  exclude_paths:
    - "**/migrations/**"
  config:
    - patterns:
        - ^import.*
        - ^from.*
      severity: minor
