version: '2'
plugins:
  test-coverage:
    enabled: true
    input:
      - coverage.xml
    output:
      format: 'lcov'
      stdout: true
    config:
      exclude_paths:
        - "**/.venv/**"
        - "**/myenv/**"
      pytest:
        enabled: true
        options:
          --randomly-seed=1
          --cov-config .coveragerc
          --cov-report xml:coverage.xml
          --cov-report term
          --cov=python_project_50
